# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: shared_libs/proto/sms.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'shared_libs/proto/sms.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bshared_libs/proto/sms.proto\x12\x03sms\"3\n\x10SingleSMSRequest\x12\x0e\n\x06mobile\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"w\n\x14\x43lassificationResult\x12\x0e\n\x06mobile\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\x12\x18\n\x10is_transactional\x18\x04 \x01(\x08\x12\x12\n\nconfidence\x18\x05 \x01(\x02\"R\n\x15SinglePredictResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12)\n\x06result\x18\x02 \x01(\x0b\x32\x19.sms.ClassificationResult2T\n\rSMSClassifier\x12\x43\n\x0e\x43lassifySingle\x12\x15.sms.SingleSMSRequest\x1a\x1a.sms.SinglePredictResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shared_libs.proto.sms_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SINGLESMSREQUEST']._serialized_start=36
  _globals['_SINGLESMSREQUEST']._serialized_end=87
  _globals['_CLASSIFICATIONRESULT']._serialized_start=89
  _globals['_CLASSIFICATIONRESULT']._serialized_end=208
  _globals['_SINGLEPREDICTRESPONSE']._serialized_start=210
  _globals['_SINGLEPREDICTRESPONSE']._serialized_end=292
  _globals['_SMSCLASSIFIER']._serialized_start=294
  _globals['_SMSCLASSIFIER']._serialized_end=378
# @@protoc_insertion_point(module_scope)
